package InternalPages;


import InternalPages.generatedailylogs;
import InternalPages.libraryDashbord;
import InternalPages.logs;
import config.dbconnector;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class dashBoard extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public dashBoard() {
        initComponents();
    }
    Color navcolor= new Color(153,153,255);
    Color headcolor= new Color(204,204,255);    
    Color bodycolor = new Color(102,102,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        mimimize = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        logs = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        generate = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bookdetails = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        log_out = new javax.swing.JButton();
        maindesktop = new javax.swing.JDesktopPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        header.setBackground(new java.awt.Color(204, 204, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 40));

        mimimize.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        mimimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mimimize.setText("—");
        mimimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mimimizeMouseClicked(evt);
            }
        });
        header.add(mimimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 50));

        jPanel1.add(header);
        header.setBounds(200, 0, 630, 50);

        navbar.setBackground(new java.awt.Color(153, 153, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logs.setBackground(new java.awt.Color(153, 153, 255));
        logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logsMouseExited(evt);
            }
        });
        logs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" LOGS");
        logs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daily logs (1).png"))); // NOI18N
        logs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        navbar.add(logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 50));

        dashboard.setBackground(new java.awt.Color(153, 153, 255));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DASHBOARD");
        dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LIBRARY ");
        dashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, 120, 28));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lib dashboard (1).png"))); // NOI18N
        dashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        navbar.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 50));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel13.setText("WELCOME!");
        navbar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 20));

        generate.setBackground(new java.awt.Color(153, 153, 255));
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generateMouseExited(evt);
            }
        });
        generate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("GENERATE ");
        generate.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 95, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DAILY LOGS ");
        generate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 95, 28));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daily logs (1).png"))); // NOI18N
        generate.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        navbar.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 50));

        bookdetails.setBackground(new java.awt.Color(153, 153, 255));
        bookdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookdetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookdetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookdetailsMouseExited(evt);
            }
        });
        bookdetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BOOK DETAILS");
        bookdetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daily logs (1).png"))); // NOI18N
        bookdetails.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        navbar.add(bookdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/USER (1).png"))); // NOI18N
        profile.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                profileAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel2.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        navbar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 80));

        firstname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        navbar.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 30));

        log_out.setBackground(new java.awt.Color(102, 102, 255));
        log_out.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        log_out.setText("LOGOUT");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        navbar.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 40));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 200, 480);

        maindesktop.setBackground(new java.awt.Color(102, 102, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("LOGGER");
        maindesktop.add(jLabel17);
        jLabel17.setBounds(0, 190, 630, 50);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 72)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("LIBRARY");
        maindesktop.add(jLabel18);
        jLabel18.setBounds(10, 170, 630, 50);

        jPanel1.add(maindesktop);
        maindesktop.setBounds(200, 50, 630, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mimimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mimimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_mimimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       int a=JOptionPane.showConfirmDialog(null, "Confirm Exit?");
       if(a==JOptionPane.YES_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_exitMouseClicked

    private void logsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseEntered
        logs.setBackground(bodycolor);
    }//GEN-LAST:event_logsMouseEntered

    private void logsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseExited
        logs.setBackground(navcolor);
    }//GEN-LAST:event_logsMouseExited

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        dashboard.setBackground(bodycolor);
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setBackground(navcolor);
    }//GEN-LAST:event_dashboardMouseExited

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        libraryDashbord lb = new libraryDashbord();
        maindesktop.add(lb).setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void generateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseEntered
        generate.setBackground(bodycolor);
    }//GEN-LAST:event_generateMouseEntered

    private void generateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseExited
        generate.setBackground(navcolor);
    }//GEN-LAST:event_generateMouseExited

    private void generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseClicked
        generatedailylogs ge = new generatedailylogs();
        maindesktop.add(ge).setVisible(true);
    }//GEN-LAST:event_generateMouseClicked

    private void logsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseClicked
        logs ul = new logs();
        maindesktop.add(ul).setVisible(true);
    }//GEN-LAST:event_logsMouseClicked

    private void bookdetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookdetailsMouseExited
        bookdetails.setBackground(navcolor);
    }//GEN-LAST:event_bookdetailsMouseExited

    private void bookdetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookdetailsMouseEntered
        bookdetails.setBackground(bodycolor);
    }//GEN-LAST:event_bookdetailsMouseEntered

    private void bookdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookdetailsMouseClicked
        details bd = new details();
        maindesktop.add(bd).setVisible(true);
    }//GEN-LAST:event_bookdetailsMouseClicked

    private void profileAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_profileAncestorAdded
   
    }//GEN-LAST:event_profileAncestorAdded

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
          /* JFileChooser browseImageFile = new JFileChooser();
           FileNameExtensionFilter fnaf = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
           browseImageFile.addChoosableFileFilter(fnaf);
           int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
           
            if (showOpenDialogue == JFileChooser.APPROVE_OPTION);
           File selectionImageFile;
        selectionImageFile = browseImageFile.getSelectedFile();
           String selectedImagePath = selectedFile.getAbsolutePath();
        String link;
        link = selectedImagePath;
            JOptionPane.showMessageDialog(null, selectedImagePath);
           
           ImageIcon ii = new ImageIcon(selectedImagePath);
           
           Image image = ii.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
           profile.setIcon(new ImageIcon(image));*/
           
    }//GEN-LAST:event_profileMouseClicked

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed

        loginForm lf = new loginForm();
           lf.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_log_outActionPerformed
/*public  ImageIcon ResizeImage(String ImagePath, byte[] pic) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(image_display.getWidth(), image_display.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}

    public byte[] imageBytes;
    String path;
    String filename=null;
    String imgPath = null;
    public byte[] person_image = null;*/
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(filter);
        int result = chooser.showSaveDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = chooser.getSelectedFile();
           String path = selectedFile.getAbsolutePath();
            image_display.setIcon(ResizeImage(path,null));
           String imgPath;
           imgPath = path;
            File f = chooser.getSelectedFile();
           String filename;
           filename = selectedFile.getAbsolutePath();
        }else{
        JOptionPane.showMessageDialog(null, "Canceled !");
        }
        
      
        try {
           String filename = null;
                File image = new File(filename);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                
                for (int readNum; (readNum=fis.read(buf)) !=-1;){
                 bos.write(buf,0,readNum);
                }
           byte[] person_image;
           person_image = bos.toByteArray();
                
        }catch(IOException e){
            System.out.println(e);
        }
        
        try{
            dbconnector dbc =new dbconnector();
            ResultSet rs = dbc.getData("SELECT FROM `U_Img` ");
            if (rs.next()){
                image_display.setIcon(ResizeImage(null,rs.getBytes("U_Img")));
            
        }
        }catch(SQLException e){
           
        }
        
        
        
        
       
        
        
        /* JFileChooser browseImageFile = new JFileChooser();
           FileNameExtensionFilter fnaf = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
           browseImageFile.addChoosableFileFilter(fnaf);
           int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
           
            if (showOpenDialogue == JFileChooser.APPROVE_OPTION);
           File selectionImageFile;
        selectionImageFile = browseImageFile.getSelectedFile();
           String selectedImagePath = selectedFile.getAbsolutePath();
        String link;
        link = selectedImagePath;
            JOptionPane.showMessageDialog(null, selectedImagePath);
           
           ImageIcon ii = new ImageIcon(selectedImagePath);
           
           Image image = ii.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
           profile.setIcon(new ImageIcon(image));*/
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookdetails;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel exit;
    public static javax.swing.JLabel firstname;
    private javax.swing.JPanel generate;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JButton log_out;
    private javax.swing.JPanel logs;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JLabel mimimize;
    private javax.swing.JPanel navbar;
    public static javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ResizeImage(String path, Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
