/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPages;

import javax.swing.JOptionPane;

/**
 *
 * @author Quines
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentname = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        timeOut = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        timeIn = new javax.swing.JTextField();
        Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        idData.setBackground(new java.awt.Color(204, 204, 255));
        idData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDataActionPerformed(evt);
            }
        });
        jPanel1.add(idData);
        idData.setBounds(110, 70, 190, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Student Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 90, 30);

        studentname.setBackground(new java.awt.Color(204, 204, 255));
        studentname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        studentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameActionPerformed(evt);
            }
        });
        jPanel1.add(studentname);
        studentname.setBounds(110, 110, 190, 30);

        ISBN.setBackground(new java.awt.Color(204, 204, 255));
        ISBN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNActionPerformed(evt);
            }
        });
        jPanel1.add(ISBN);
        ISBN.setBounds(110, 190, 190, 30);

        timeOut.setBackground(new java.awt.Color(204, 204, 255));
        timeOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOutActionPerformed(evt);
            }
        });
        jPanel1.add(timeOut);
        timeOut.setBounds(110, 330, 190, 30);

        gender.setBackground(new java.awt.Color(204, 204, 255));
        gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(110, 150, 190, 30);

        bookname.setBackground(new java.awt.Color(204, 204, 255));
        bookname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameActionPerformed(evt);
            }
        });
        jPanel1.add(bookname);
        bookname.setBounds(110, 240, 190, 30);

        timeIn.setBackground(new java.awt.Color(204, 204, 255));
        timeIn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInActionPerformed(evt);
            }
        });
        jPanel1.add(timeIn);
        timeIn.setBounds(110, 280, 190, 30);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print);
        Print.setBounds(350, 400, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDataActionPerformed

    private void studentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameActionPerformed

    private void ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNActionPerformed

    private void timeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeOutActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknameActionPerformed

    private void timeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeInActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
      int b = JOptionPane.showConfirmDialog(null, "Are you sure you want to print?");
        if (b == JOptionPane.YES_OPTION) {
            forprint ot = new forprint();

           ot.text.setText("                                             \n\n"
                    + "                                           EMPLOYEE REPORT   \n\n\n"
                    + "■  PERSONAL DETAILS   \n\n"
                    + " ID                        :         " + idData.getText() + "\n\n"
                    + "STUDENT NAME                           :         " + studentname.getText() + "\n\n"
                    + "GENDER                           :         " + gender.getText() + "\n\n"
                    + "ISBN                                    :         " + ISBN.getText() + "\n\n"
                    + "BOOK NAME                               :         " + bookname.getText() + " \n\n"
                    + "Time In                            :         " + timeIn.getText() + "\n\n"
                    + "Time Out                           :         " + timeOut.getText() + "\n\n");

            ot.setVisible(true);
            this.dispose();
           ot.text.setEditable(true);
        } 
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ISBN;
    private javax.swing.JButton Print;
    public javax.swing.JTextField bookname;
    public javax.swing.JTextField gender;
    public javax.swing.JTextField idData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField studentname;
    public javax.swing.JTextField timeIn;
    public javax.swing.JTextField timeOut;
    // End of variables declaration//GEN-END:variables
}
